<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annie Waldherr">
<meta name="dcterms.date" content="2023-11-20">

<title>Exercise 4: ANOVA II – R Tutorials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R Tutorials</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">German</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index1.html"> 
<span class="menu-text">English</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#aims-overview" id="toc-aims-overview" class="nav-link active" data-scroll-target="#aims-overview">Aims &amp; overview</a></li>
  <li><a href="#the-working-directory" id="toc-the-working-directory" class="nav-link" data-scroll-target="#the-working-directory">The working directory</a></li>
  <li><a href="#install-and-load-packages" id="toc-install-and-load-packages" class="nav-link" data-scroll-target="#install-and-load-packages">Install and load packages</a></li>
  <li><a href="#read-data" id="toc-read-data" class="nav-link" data-scroll-target="#read-data">Read data</a></li>
  <li><a href="#define-ivs-and-dvs" id="toc-define-ivs-and-dvs" class="nav-link" data-scroll-target="#define-ivs-and-dvs">Define IVs and DVs</a></li>
  <li><a href="#descriptive-statistics-of-dv" id="toc-descriptive-statistics-of-dv" class="nav-link" data-scroll-target="#descriptive-statistics-of-dv">Descriptive statistics of DV</a></li>
  <li><a href="#levenes-test-for-checking-homogeneity-of-variance" id="toc-levenes-test-for-checking-homogeneity-of-variance" class="nav-link" data-scroll-target="#levenes-test-for-checking-homogeneity-of-variance">Levene’s test for checking homogeneity of variance</a></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova">Two-way ANOVA</a></li>
  <li><a href="#effect-sizes" id="toc-effect-sizes" class="nav-link" data-scroll-target="#effect-sizes">Effect sizes</a></li>
  <li><a href="#report-results" id="toc-report-results" class="nav-link" data-scroll-target="#report-results">Report results</a></li>
  <li><a href="#visualization-of-the-effects" id="toc-visualization-of-the-effects" class="nav-link" data-scroll-target="#visualization-of-the-effects">Visualization of the effects</a></li>
  <li><a href="#for-further-reading" id="toc-for-further-reading" class="nav-link" data-scroll-target="#for-further-reading">For further reading</a></li>
  <li><a href="#assignment-4" id="toc-assignment-4" class="nav-link" data-scroll-target="#assignment-4">Assignment 4</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise 4: ANOVA II</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Annie Waldherr </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="aims-overview" class="level2">
<h2 class="anchored" data-anchor-id="aims-overview">Aims &amp; overview</h2>
<p>This tutorial follows up on the tutorial ANOVA I and extends it to a two-way analysis of variance (ANOVA). You will learn how to:</p>
<ul>
<li>perform and interpret a two-way ANOVA</li>
<li>calculate and interpret effect sizes</li>
<li>plot effect sizes with error bars</li>
<li>plot interaction diagrams</li>
</ul>
</section>
<section id="the-working-directory" class="level2">
<h2 class="anchored" data-anchor-id="the-working-directory">The working directory</h2>
<p>As always, we first check with “getwd()” where our working directory is located. All scripts and data sets we want to work with should be placed in this folder. If it’s not correct we can set a new working directory as we learnt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## check working directory</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/antje/Documents/studium PUK/Master-Publizistik/STUDIENASSISTENZ/Test Tutorial"</code></pre>
</div>
</div>
</section>
<section id="install-and-load-packages" class="level2">
<h2 class="anchored" data-anchor-id="install-and-load-packages">Install and load packages</h2>
<p>In the following, we need the same packages as in exercise 3. We load these again with the “pacman” package, which we already installed in exercise 2 (t-test).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">##install and load packages</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>); <span class="fu">library</span>(pacman)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: pacman</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(mosaic, knitr, tidyverse, effectsize, broom, car, ggpubr, PMCMRplus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-data" class="level2">
<h2 class="anchored" data-anchor-id="read-data">Read data</h2>
<p>In this exercise, we expand our ANOVA to include more variables. To do this, we load a new data set “Advertisements2.csv”. This contains the same data as in exercise 3, plus the new variables “attention” and “gender”. Remember: It’s a hypothetical data set for an experiment in which different groups of participants were either presented radio, print or TV ads. It was then recorded how many advertising messages the test persons remembered (variable “recall”). Load the “Advertisements2.csv” data set from the respective folder in Moodle and place it in your working directory.</p>
<p><strong>Caution!</strong>: If we open the data set with a simple data editor, we see that the semicolon is used as a separator here as well. Therefore, in the following command we use the “sep” argument again, with which we can specify the separator if it differs from the default (comma).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load dataset</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Advertisements2.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#inspect dataset</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15
Columns: 4
$ adformat  &lt;int&gt; 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3
$ recall    &lt;int&gt; 5, 7, 3, 4, 6, 12, 7, 8, 10, 13, 12, 11, 12, 12, 13
$ attention &lt;int&gt; 1, 2, 3, 5, 6, 6, 3, 4, 6, 6, 5, 4, 5, 6, 5
$ gender    &lt;int&gt; 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  adformat recall attention gender
1        1      5         1      1
2        1      7         2      0
3        1      3         3      1
4        1      4         5      1
5        1      6         6      1
6        2     12         6      0</code></pre>
</div>
</div>
<p>With the “View” function we can look at the data in a separate window.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#open Viewer </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-ivs-and-dvs" class="level2">
<h2 class="anchored" data-anchor-id="define-ivs-and-dvs">Define IVs and DVs</h2>
<p>We want to carry out a two-way ANOVA and check whether the recall of the respondents differs significantly according to the type of advertising and gender. The variables “adformat” and “gender” are therefore our IVs and must be nominally scaled. In the above output of the “glimpse()” function, we see that the two variables are encoded numerically (of type “integer” int), even though they are our grouping variables. We, thus, need to convert them into factors using the “factor” function.</p>
<p>Let’s recode the gender variable,first. It’s dichotomous with 0 = male and 1 = female. Since R sometimes interprets null values as missing values, we better recode this variable to replace all 0s with the value 1 and all 1s with the value 2. 1 then means male, 2 female.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#recode variable "gender"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">Recode</span>((df<span class="sc">$</span>gender), </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">'0 = 1; 1 = 2'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15
Columns: 4
$ adformat  &lt;int&gt; 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3
$ recall    &lt;int&gt; 5, 7, 3, 4, 6, 12, 7, 8, 10, 13, 12, 11, 12, 12, 13
$ attention &lt;int&gt; 1, 2, 3, 5, 6, 6, 3, 4, 6, 6, 5, 4, 5, 6, 5
$ gender    &lt;dbl&gt; 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2</code></pre>
</div>
</div>
<p>Now we define the IVs and DVs and convert the IVs to factors with the function “factor”. We use the “levels” and “labels” arguments to store the three factor levels with their associated labels.</p>
<ul>
<li>“adformat”: Value 1 is assigned to “radio”, value 2 to “print” and value 3 to “TV”.</li>
<li>“gender”: Value 1 stands for “male”, value 2 for “female”.</li>
</ul>
<p><strong>Attention</strong>! If the values of the IVs are already as text, i.e., they are of type “character” (chr), then, we can simply use the “as.factor()” function.</p>
<p>The variable “recall” is our DV, and it’s already a metric variable as requested.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#define IVs and convert into factors</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>iv1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>adformat, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span> (<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Radio"</span>, <span class="st">"Print"</span>, <span class="st">"TV"</span>)) </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>iv2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>gender, </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span> (<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)) </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Define DV</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>dv <span class="ot">&lt;-</span> df<span class="sc">$</span>recall</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15
Columns: 7
$ adformat  &lt;int&gt; 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3
$ recall    &lt;int&gt; 5, 7, 3, 4, 6, 12, 7, 8, 10, 13, 12, 11, 12, 12, 13
$ attention &lt;int&gt; 1, 2, 3, 5, 6, 6, 3, 4, 6, 6, 5, 4, 5, 6, 5
$ gender    &lt;dbl&gt; 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2
$ iv1       &lt;fct&gt; Radio, Radio, Radio, Radio, Radio, Print, Print, Print, Prin…
$ iv2       &lt;fct&gt; Female, Male, Female, Female, Female, Male, Male, Female, Ma…
$ dv        &lt;int&gt; 5, 7, 3, 4, 6, 12, 7, 8, 10, 13, 12, 11, 12, 12, 13</code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics-of-dv" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-of-dv">Descriptive statistics of DV</h2>
<p>Now let’s use the “favstats” function to generate the most important descriptive statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#define labels</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>label_iv1 <span class="ot">&lt;-</span> <span class="st">"Advertising Format"</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>label_iv2 <span class="ot">&lt;-</span> <span class="st">"Gender"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>label_dv <span class="ot">&lt;-</span> <span class="st">"Recall"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate descriptive statistics</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>des_stat1 <span class="ot">&lt;-</span> <span class="fu">favstats</span>(df<span class="sc">$</span>dv <span class="sc">~</span> df<span class="sc">$</span>iv1)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>des_stat2 <span class="ot">&lt;-</span> <span class="fu">favstats</span>(df<span class="sc">$</span>dv <span class="sc">~</span> df<span class="sc">$</span>iv2)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># create tables</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span> (des_stat1,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">col.names =</span> <span class="fu">c</span>(label_iv1,<span class="st">"Minimum"</span>, <span class="st">"1.Quartile"</span>, </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Median"</span>, <span class="st">"3.Quartile"</span>, <span class="st">"Maximum"</span>, </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"M"</span>, <span class="st">"SD"</span>, <span class="st">"N"</span>, <span class="st">"Missing"</span> ),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Advertising Format</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">1.Quartile</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">3.Quartile</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Radio</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Print</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2.55</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TV</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span> (des_stat2,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">col.names =</span> <span class="fu">c</span>(label_iv2,<span class="st">"Minimum"</span>, <span class="st">"1.Quartile"</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Median"</span>, <span class="st">"3.Quartile"</span>, <span class="st">"Maximum"</span>, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"M"</span>, <span class="st">"SD"</span>, <span class="st">"N"</span>, <span class="st">"Missing"</span> ),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">1.Quartile</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">3.Quartile</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">10.17</td>
<td style="text-align: right;">2.64</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8.22</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We see again that, on average, radio ads are recalled less than print and TV ads. In addition, TV ads are recalled a little more than print ads. The statistics for our IV “gender” show that men recall a bit more advertising messages on average than women. However, this does not mean that these differences are also statistically significant. In order to check this, we carry out a two-way ANOVA below.</p>
<p>First, however, we group the data according to the two IVs with the “group_by” function and use the “summarize” function to calculate summary statistics for our DV: mean values (mean = mean (dv)), standard deviations (std_dev = sd(dv)) and the number of values per group (count = n()). To link the different working steps together, we use the pipe again (%&gt;%). We store the statistics in a new object called “df_by_group”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># statistics by group</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df_by_group <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(iv1, iv2) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(dv), <span class="at">std_dev =</span> <span class="fu">sd</span>(dv), <span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'iv1'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_by_group</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   iv1 [3]
  iv1   iv2     mean std_dev count
  &lt;fct&gt; &lt;fct&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;
1 Radio Male     7    NA         1
2 Radio Female   4.5   1.29      4
3 Print Male    10.5   2.65      4
4 Print Female   8    NA         1
5 TV    Male    12    NA         1
6 TV    Female  12     0.816     4</code></pre>
</div>
</div>
<p>In the “mean” column, we definitely see differences in the average recall (our DV!) for radio and print advertising. For TV ads, however, the means for male and female participants are exactly the same.</p>
<p><strong>Question</strong>: Why is there no standard deviation for three of the groups?</p>
</section>
<section id="levenes-test-for-checking-homogeneity-of-variance" class="level2">
<h2 class="anchored" data-anchor-id="levenes-test-for-checking-homogeneity-of-variance">Levene’s test for checking homogeneity of variance</h2>
<p>Before we carry out the ANOVA, we have to check whether the condition of homogeneity of variance is met. To do this, we use Levene’s test again, which tests whether the variances in all six groups differ significantly from one another. The commands below are already known from the previous exercises. But since we now have two IVs, we combine them in the form: iv1*iv2</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(iv1, iv2, dv) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">leveneTest</span>(dv <span class="sc">~</span> iv1<span class="sc">*</span>iv2, <span class="at">data =</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  5   1.785  0.212
       9               </code></pre>
</div>
</div>
<p>Levene’s test is not significant (F(5,9) = 1.78, p = 0.212) because p &gt; 0.05. Thus, we can retain the null hypothesis, assume homogeneity of variance, and proceed with the analysis of variance.</p>
</section>
<section id="two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="two-way-anova">Two-way ANOVA</h2>
<p>For conducting the ANOVA, we use the “aov” function again. Also in this function we enter the two IVs linked with *. This way, we make sure that both factors are tested individually for their respective main effects as well as in combination, i.e., as an interaction effect. If you want to check the two factors only separately, without calculating an interaction effect, we use a +.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(df, iv1, iv2, dv)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(dv <span class="sc">~</span> iv1<span class="sc">*</span>iv2, <span class="at">data =</span> df)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
iv1          2 130.00   65.00  20.893 0.000415 ***
iv2          1   6.67    6.67   2.143 0.177268    
iv1:iv2      2   3.33    1.67   0.536 0.602811    
Residuals    9  28.00    3.11                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A table with four rows is displayed in the output. The columns correspond exactly to those of the one-way ANOVA (see Exercise 3). The line “iv1” contains the statistics for the main effect of our first IV (adformat), the line “iv2” contains the statistics for the main effect of our second IV (gender). We see in the last column that the main effect for IV1 is highly significant with p &lt; 0.001. The main effect for IV2, in contrast, is not significant (p=0.18 and thus &gt; 0.05).</p>
<p>In the third line, we see the interaction effect. This is also not significant in our example, i.e.&nbsp;gender and form of advertising do not have any specific effects in certain combinations of the two variables.</p>
<p>The values in the fourth row (residuals) refer to the within-group variance that cannot be explained by the IVs and/or their interaction effect (sometimes called error variance).</p>
</section>
<section id="effect-sizes" class="level2">
<h2 class="anchored" data-anchor-id="effect-sizes">Effect sizes</h2>
<p>In order to determine exactly how large the influence of the IVs on the DV is and to be able to compare the size of the various significant (!) effects with one another, we determine the effect sizes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter | Eta2 (partial) |       95% CI
-----------------------------------------
iv1       |           0.82 | [0.54, 1.00]
iv2       |           0.19 | [0.00, 1.00]
iv1:iv2   |           0.11 | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p><strong>Important!</strong> We only interpret the effect sizes of the significant effects, in this case, for the main effect of IV1. The eta squared is 0.82. According to Cohen, this is a large effect (small = 0.01; medium = 0.06; large = 0.14).</p>
<p><strong>Note:</strong> The partial eta squares are calculated here using the Type1 method. This means that the effect sizes account for the variance explained by the previous variables in the model, i.e.&nbsp;the partial eta square of IV2 measures the proportion of variance explained by IV2 of the total variance remaining after accounting for the variance already explained by IV1, and so forth.</p>
</section>
<section id="report-results" class="level2">
<h2 class="anchored" data-anchor-id="report-results">Report results</h2>
<p>We report the results of the two-way ANOVA as follows:</p>
<p>The main effect of the advertising format on recall is significant. The number of recalled advertising messages differs statistically significantly for the different advertising formats, F (2.9) = 20.89, p &lt; 0.001, η² = 0.82. The main effect of gender (p = 0.18) and the interaction effect of advertising format and gender (p = 0.60) are not significant.</p>
<p>If we hadn’t already done this in Exercise 3, we would now proceed with the post-hoc tests for the significant main effect to find out which of the groups are significantly different from each other.</p>
</section>
<section id="visualization-of-the-effects" class="level2">
<h2 class="anchored" data-anchor-id="visualization-of-the-effects">Visualization of the effects</h2>
<p>We now create a line chart with error bars to visualize the main effect of our IV1 (adformat). First, we create a variable called “Title” and assign to it the title we want to give the figure: “Effect of Advertising Format”</p>
<p>Then, we use the “ggline” function from the “ggpubr” package to create a line chart. We take our data set “df” and, first, remove all rows with missing values for our IV1 and DV with “drop_na()”. Then, we specify which variables to use for the x-axis and the y-axis of the chart. We put the IV1 on the x-axis and the DV on the y-axis.</p>
<p>With the argument “title = Title” we specify the title chosen above as the title for the graph and add the 95% confidence intervals as error bars with “add” (mean_ci). Finally, we use “xlab” and “ylab” to set the labels for the axes of the chart, referencing our labels we created above (see the “Descriptive Statistics” code chunk).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>Title <span class="ot">&lt;-</span> <span class="st">"Effect of Advertising Format"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggline</span>(df <span class="sc">%&gt;%</span> <span class="fu">drop_na</span> (dv, iv1),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">"iv1"</span>, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"dv"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> Title,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">add =</span> <span class="st">"mean_ci"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> label_iv1,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> label_dv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercise4_files/figure-html/error bars-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As a result, we get a line chart showing the mean values of the recall variable (DV) for the different formats of advertising (IV1). The confidence intervals indicate the range of values in which the true mean values lie with 95% certainty. These vary in size for the various formats of advertising, and they partially overlap, particularly for print and TV. This suggests that the differences in the means of these two formats of advertising are not significant.</p>
<p>An interaction diagram is suitable for visualizing both main effects and their potential interaction. We create such a diagram with the “interaction.plot” function from the “stats” package. We define the following arguments:</p>
<ul>
<li>df$iv1: The values of IV1 are displayed on the x-axis.</li>
<li>df$iv2: The values of IV2 are used to create different lines in the plot.</li>
<li>df$dv: The values of our DV are displayed on the y-axis.</li>
<li>fun = mean: The “mean” function is used to calculate the mean values of DV for each factor level of IV1 and IV2. These are used to create the lines in the plot.</li>
<li>ylab = label_iv1: The label for the y-axis is set to “label_iv1” which we set above.</li>
<li>xlab = label_dv: The label for the x-axis is set to “label_dv”, which we also defined above.</li>
<li>trace.label = label_iv2: The legend for the lines in the plot is labeled with “label_iv2”.</li>
<li>col = c(“#0198f9”, “#f95801”): The colors for the lines are set to blue and orange.</li>
<li>lty = 1: The line type for the lines is set as a solid line (lty=1).</li>
<li>lwd = 2: The thickness of the lines is set to 2.</li>
<li>xtick = TRUE: Grid lines for the x-axis are displayed.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>iv1, df<span class="sc">$</span>iv2, df<span class="sc">$</span>dv,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="at">fun =</span> mean,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="at">ylab =</span> label_dv,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> label_iv1,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="at">trace.label =</span> label_iv2,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#0198f9"</span>, <span class="st">"#f95801"</span>),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">1</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="at">xtick =</span> T,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercise4_files/figure-html/interaction diagramm-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows what we could already read from the tables of the mean values. While there are gender differences in the mean values for radio and print ads, they disappear for TV ads. However, from our ANOVA we already know that neither the main effect for gender nor the interaction effect of our two IVs are significant. We therefore do not further interpret the interaction diagram at this point.</p>
</section>
<section id="for-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="for-further-reading">For further reading</h2>
<p>Chapters 10 and 12 in: Fields, A. (2012). Discovering statistics using R. Sage.</p>
</section>
<section id="assignment-4" class="level2">
<h2 class="anchored" data-anchor-id="assignment-4">Assignment 4</h2>
<p>It’s your turn! In a survey on cinema reception, the respondents’ sense of presence was measured (“At the end of a film I have the feeling of waking up from a dream, I am completely drawn into the film, I am completely captivated by the story, I let go completely”).</p>
<p><strong>Your task is to find out whether the sense of presence depends on gender (female=1; male=2) and education (low=0; high=1).</strong></p>
<ol type="1">
<li>Open the “Cinema.csv” data set from our Moodle course in R-Studio.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Read and inspect data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Determine independent and dependent variables. Check the variables for their measurement scales, and, if necessary, recode them accordingly.</li>
</ol>
<p>Answer: …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define IVs and DV, convert to factor if necessary</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Check whether the data meet the requirement of homogeneity of variances. Perform the appropriate test and interpret the result.</li>
</ol>
<p>Answer: …</p>
<ol start="4" type="1">
<li>Now carry out a two-way ANOVA. How do you interpret the results? Consider each effect individually.</li>
</ol>
<p>Answer: …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#carry out variance analysis</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" type="1">
<li>Calculate and interpret the effect sizes.</li>
</ol>
<p>Answer: …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate effect sizes</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="6" type="1">
<li>Did you find a significant interaction? If yes, plot the interaction effect and explain the nature of the interaction. If not, then only plot the significant main effects with error bars.</li>
</ol>
<p>Answer: …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#interaction plot or line graph</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Important!</strong> Save the customized markdown with a filename like this: Last_Name_Exercise4.Rmd Upload this file to the designated folder in Moodle.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>