<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annie Waldherr">
<meta name="dcterms.date" content="2024-12-10">

<title>Übung 7: Moderation – R Tutorials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R Tutorials</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lernziele-und-überblick" id="toc-lernziele-und-überblick" class="nav-link active" data-scroll-target="#lernziele-und-überblick">Lernziele und Überblick</a></li>
  <li><a href="#das-arbeitsverzeichnis" id="toc-das-arbeitsverzeichnis" class="nav-link" data-scroll-target="#das-arbeitsverzeichnis">Das Arbeitsverzeichnis</a></li>
  <li><a href="#pakete-installieren-und-laden" id="toc-pakete-installieren-und-laden" class="nav-link" data-scroll-target="#pakete-installieren-und-laden">Pakete installieren und laden</a></li>
  <li><a href="#process-laden" id="toc-process-laden" class="nav-link" data-scroll-target="#process-laden">PROCESS laden</a></li>
  <li><a href="#daten-einlesen" id="toc-daten-einlesen" class="nav-link" data-scroll-target="#daten-einlesen">Daten einlesen</a></li>
  <li><a href="#variablen-definieren" id="toc-variablen-definieren" class="nav-link" data-scroll-target="#variablen-definieren">Variablen definieren</a></li>
  <li><a href="#datenexploration" id="toc-datenexploration" class="nav-link" data-scroll-target="#datenexploration">Datenexploration</a></li>
  <li><a href="#moderationsanalyse" id="toc-moderationsanalyse" class="nav-link" data-scroll-target="#moderationsanalyse">Moderationsanalyse</a></li>
  <li><a href="#zentrierung-am-mittelwert" id="toc-zentrierung-am-mittelwert" class="nav-link" data-scroll-target="#zentrierung-am-mittelwert">Zentrierung am Mittelwert</a></li>
  <li><a href="#visualisierung-des-interaktionseffekts" id="toc-visualisierung-des-interaktionseffekts" class="nav-link" data-scroll-target="#visualisierung-des-interaktionseffekts">Visualisierung des Interaktionseffekts</a></li>
  <li><a href="#untersuchung-des-interaktionseffekts" id="toc-untersuchung-des-interaktionseffekts" class="nav-link" data-scroll-target="#untersuchung-des-interaktionseffekts">Untersuchung des Interaktionseffekts</a></li>
  <li><a href="#zum-nachlesen" id="toc-zum-nachlesen" class="nav-link" data-scroll-target="#zum-nachlesen">Zum Nachlesen</a></li>
  <li><a href="#hausübung-7" id="toc-hausübung-7" class="nav-link" data-scroll-target="#hausübung-7">Hausübung 7</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Übung 7: Moderation</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Annie Waldherr </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="lernziele-und-überblick" class="level2">
<h2 class="anchored" data-anchor-id="lernziele-und-überblick">Lernziele und Überblick</h2>
<p>In diesem Tutorial lernen Sie - ein einfaches Moderationsmodell mit Hilfe von PROCESS zu berechnen, - die Ergebnisse zu interpretieren, - eine Mittelwertzentrierung der Variablen durchzuführen, - Moderationseffekte zu visualisieren und genauer zu untersuchen.</p>
</section>
<section id="das-arbeitsverzeichnis" class="level2">
<h2 class="anchored" data-anchor-id="das-arbeitsverzeichnis">Das Arbeitsverzeichnis</h2>
<p>Wie immer prüfen wir zuerst mit “getwd()”, unter welchem Pfad unser Arbeitsverzeichnis ist. Alle Skripte und Datensätze, mit denen wir arbeiten wollen, sollten in diesem Ordner abgelegt sein.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Arbeitsverzeichnis checken</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/antje/Documents/studium PUK/Master-Publizistik/STUDIENASSISTENZ/Test Tutorial"</code></pre>
</div>
</div>
</section>
<section id="pakete-installieren-und-laden" class="level2">
<h2 class="anchored" data-anchor-id="pakete-installieren-und-laden">Pakete installieren und laden</h2>
<p>Dann laden wir wieder mit dem Paket “pacman” die nötigen R-Pakete.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Pakete installieren und laden</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>); <span class="fu">library</span>(pacman)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: pacman</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(tidyverse, knitr, mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="process-laden" class="level2">
<h2 class="anchored" data-anchor-id="process-laden">PROCESS laden</h2>
<p>Laden Sie aus Moodle (Ordner „Uebung7“) das PROCESS-Skript für R herunter. Das Skript wurde vom Forscher Andrew F. Hayes geschrieben und ist auch unter diesem Link verfügbar: <a href="https://www.PROCESSmacro.org/download.html" class="uri">https://www.PROCESSmacro.org/download.html</a></p>
<p>Speichern Sie die Datei „process.R“ in Ihrem Arbeitsverzeichnis und führen Sie dann den folgenden Code aus, um die PROCESS Funktion zu laden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"process.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
 
PROCESS is now ready for use.
Copyright 2013-2025 by Andrew F. Hayes ALL RIGHTS RESERVED
Workshop schedule at haskayne.ucalgary.ca/CCRAM 
Information about PROCESS available at processmacro.org/faq.html </code></pre>
</div>
</div>
</section>
<section id="daten-einlesen" class="level2">
<h2 class="anchored" data-anchor-id="daten-einlesen">Daten einlesen</h2>
<p>Das Beispiel, das Hayes (2022) auch in seinem Buch verwendet (siehe Referenz unten), basiert auf einer Studie von Chapman und Lickel (2016) mit insgesamt 211 Personen, die alle einen Artikel über die Hungersnot in Afrika zu lesen bekamen, die durch die Dürre in der Region verursacht wurde. Die Hälfte der Teilnehmenden erhielt zusätzlich die Information, dass der Klimawandel die Dürre verursachte, während die übrigen Teilnehmenden keine Informationen über die Ursache der Dürre bekamen: Variable “frame” mit 1=Klimawandel und 0=natürliche Ursache.</p>
<p>Nachdem sie den Artikel gelesen hatten, beantworteten die Proband:innen eine Reihe von Fragen, inwiefern sie verschiedenen Rechtfertigungen zustimmten, den Opfern der Hungersnot nicht zu helfen (Variable “justify”). Höhere Werte bedeuten ein stärkeres Gefühl, dass die Hilfe für die Opfer nicht gerechtfertigt war.</p>
<p>Schließlich beantworteten die Teilnehmenden noch Fragen zu ihrer Überzeugung, dass der Klimawandel existiert (Variable “sceptic”). Je höher der Wert, desto skeptischer ist die Person in Bezug auf den Klimawandel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datensatz laden</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"disaster.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datensatz inspizieren</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Frage</strong>: Welches Skalenniveau haben die Variablen?</p>
</section>
<section id="variablen-definieren" class="level2">
<h2 class="anchored" data-anchor-id="variablen-definieren">Variablen definieren</h2>
<p>Wir wollen nun herausfinden, inwiefern das Framing der Katastrophe als durch den Klimawandel verursacht (UV) die Rechtfertigungen der Menschen beeinflusst, nicht zu helfen (AV), und ob dieser Effekt abhängig von der Skepsis einer Person gegenüber dem Klimawandel ist (Moderationseffekt)?</p>
<p>Mit dem unten stehenden Code, der Ihnen aus den vorigen Übungen bekannt ist, definieren wir unsere UV und AV und vergeben die zugehörigen Labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#UV, AV und Moderator definieren</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>uv <span class="ot">&lt;-</span> df<span class="sc">$</span>frame</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>av <span class="ot">&lt;-</span> df<span class="sc">$</span>justify</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>W <span class="ot">&lt;-</span> df<span class="sc">$</span>skeptic</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Labels vergeben</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>label_uv <span class="ot">&lt;-</span> <span class="st">"Frame"</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>label_av <span class="ot">&lt;-</span> <span class="st">"Rechtfertigung"</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>label_W <span class="ot">&lt;-</span> <span class="st">"Klimaskeptik"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 211
Columns: 8
$ id      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ frame   &lt;int&gt; 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,…
$ donate  &lt;dbl&gt; 5.6, 4.2, 4.2, 4.6, 3.0, 5.0, 4.8, 6.0, 4.2, 4.4, 5.8, 6.2, 6.…
$ justify &lt;dbl&gt; 2.95, 2.85, 3.00, 3.30, 5.00, 3.20, 2.90, 1.40, 3.25, 3.55, 1.…
$ skeptic &lt;dbl&gt; 1.8, 5.2, 3.2, 1.0, 7.6, 4.2, 4.2, 1.2, 1.8, 8.8, 1.0, 5.4, 2.…
$ uv      &lt;int&gt; 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,…
$ av      &lt;dbl&gt; 2.95, 2.85, 3.00, 3.30, 5.00, 3.20, 2.90, 1.40, 3.25, 3.55, 1.…
$ W       &lt;dbl&gt; 1.8, 5.2, 3.2, 1.0, 7.6, 4.2, 4.2, 1.2, 1.8, 8.8, 1.0, 5.4, 2.…</code></pre>
</div>
</div>
</section>
<section id="datenexploration" class="level2">
<h2 class="anchored" data-anchor-id="datenexploration">Datenexploration</h2>
<p>Um einen ersten Eindruck über die Verteilungen der Daten zu gewinnen, erstellen wir Boxplots für die beiden metrischen Variablen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df<span class="sc">$</span>av, <span class="at">main =</span> label_av)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uebung7_files/figure-html/Boxplots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df<span class="sc">$</span>W, <span class="at">main =</span> label_W)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uebung7_files/figure-html/Boxplots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Zudem lassen wir uns die deskriptiven Statistiken für die Gruppen nach Experimentalbedingung ausgeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Deskriptive Statistiken berechnen</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>des_stat1 <span class="ot">&lt;-</span> <span class="fu">favstats</span>(df<span class="sc">$</span>av <span class="sc">~</span> df<span class="sc">$</span>uv)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabelle erstellen</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span> (des_stat1,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">col.names =</span> <span class="fu">c</span>(label_uv,<span class="st">"Minimum"</span>, <span class="st">"1.Quartil"</span>, </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Median"</span>, <span class="st">"3.Quartil"</span>, <span class="st">"Maximum"</span>, </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"M"</span>, <span class="st">"SD"</span>, <span class="st">"N"</span>, <span class="st">"Fehlend"</span> ),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Frame</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">1.Quartil</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">3.Quartil</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Fehlend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.20</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">6.80</td>
<td style="text-align: right;">2.94</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Die Gruppenmittelwerte deuten darauf hin, dass Teilnehmende, die einen Artikel lasen, in dem die Dürre auf den Klimawandel zurückgeführt wurde, den Rechtfertigungen für die Zurückhaltung von Hilfe stärker zustimmten, als die Teilnehmenden der Kontrollgruppe. Ein einfacher t-Test ergibt jedoch, dass dieser Unterschied statistisch nicht signifikant ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(av <span class="sc">~</span> uv, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  av by uv
t = -1.0413, df = 196.12, p-value = 0.299
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.3888410  0.1201029
sample estimates:
mean in group 0 mean in group 1 
       2.802364        2.936733 </code></pre>
</div>
</div>
<p>Es könnte aber sein, dass der verwendete Frame die Teilnehmenden der Studie auf unterschiedliche Weise beeinflusst hat, je nachdem ob sie dem Klimawandel skeptisch gegenüber stehen oder nicht. Um das herauszufinden, müssen wir einen Moderationseffekt prüfen (oder anders formuliert: einen Interaktionseffekt).</p>
<p>Bevor wir die Analyse fortsetzen, sollten wir aber gegebenenfalls Fälle mit fehlenden Werten aus der weiteren Analyse ausschließen. Dies ist für unseren Beispieldatensatz nicht relevant, aber der Vollständigkeit halber findet sich der notwendige Code-Chunk hier:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fälle mit fehlenden Werten ausschließen</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(df, uv, av, W)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="moderationsanalyse" class="level2">
<h2 class="anchored" data-anchor-id="moderationsanalyse">Moderationsanalyse</h2>
<p>Mit dem folgenden Code wenden wir ein Moderationsmodell auf die Daten an. Hierzu nutzen wir die Funktion “process” aus dem heruntergeladenen PROCESS-Skript von Andrew Hayes. Wir definieren die Variablen y (=av), x (=uv), und w (=unsere Moderatorvariable W) und wählen “model = 1”. Mit dem Argument “decimals = 10.2” werden Dezimalzahlen auf zwei Stellen hinter dem Komma gerundet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"av"</span>, <span class="at">x =</span> <span class="st">"uv"</span>, <span class="at">w =</span> <span class="st">"W"</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">1</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.2</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
           
  Model: 1 
      Y: av
      X: uv
      W: W 

Sample size: 211


*********************************************************************** 
Outcome Variable: av

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.50       0.25       0.66      22.54       3.00     207.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       2.45       0.15      16.45       0.00       2.16       2.75
uv            -0.56       0.22      -2.58       0.01      -0.99      -0.13
W              0.11       0.04       2.76       0.01       0.03       0.18
int_1          0.20       0.06       3.64       0.00       0.09       0.31

Product terms key:
int_1  :  uv  x  W      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.05      13.25       1.00     207.00       0.00
----------
Focal predictor: uv (X)
      Moderator: W (W)

Conditional effects of the focal predictor at values of the moderator(s):
           W     effect         se          t          p       LLCI       ULCI
        1.59      -0.24       0.15      -1.62       0.11      -0.54       0.05
        2.80       0.00       0.12       0.01       0.99      -0.23       0.23
        5.20       0.48       0.15       3.21       0.00       0.19       0.78

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>Die Ausgabe enthält im oberen Teil die Modellzusammenfassung. Wir sehen, dass das Modell statistisch signifkant ist (p=0.00) und 25% Prozent der Varianz in den Daten aufklärt (R-sq=0.25).</p>
<p>Darauf folgt eine Tabelle mit den Modellkoeffizienten. Diese enthält die Regressionskoeffizienten (B-Werte) der UV und des Moderators W sowie den Interaktionseffekt von UV*W. Alle drei Koeffizienten sind statistisch hoch signifikant mit p&lt;0.01. Der signifikante Interaktionseffekt bedeutet, dass der Einfluss des Framings auf die Rechtfertigung fehlender Hilfe durch die Einstellung der Proband:innen zum Klimawandel moderiert wird.</p>
<p>Unter “test(s) of highest order unconditional interaction(s)” erfahren wir, dass wir durch die Aufnahme des Interaktionsterms (d.h. des Moderators) signifikant mehr Varianz aufklären können als ohne diesen Term, und dass dieser Zuwachs in R-Quadrat 4.8% beträgt (r2-chng = 0.048).</p>
<p><strong>Vorsicht</strong>: Die Koeffizienten für die AV und den Moderator dürfen wir leider nicht so interpretieren, wie wir es gewohnt sind, denn es handelt sich um sogenannte konditionale Effekte. Im multiplen Regressionsmodell geben die B-Werte an, um wie viele Skalenpunkte die AV in Abhängigkeit einer Variablen (UV oder W) steigt, und zwar um den Effekt der anderen Variable bereinigt (partielle Effekte). Im Moderationsmodell geben die Koeffizienten den Einfluss einer Variablen auf die AV an, unter der Bedingung, dass die andere Variable gleich Null(!) ist. Diese Haupteffekte können wir in der Regel inhaltlich nicht sinnvoll interpretieren, es sei denn die Null hat auf der Messskala eine substanzielle Bedeutung (wie in unserem Beispiel frame=0).</p>
</section>
<section id="zentrierung-am-mittelwert" class="level2">
<h2 class="anchored" data-anchor-id="zentrierung-am-mittelwert">Zentrierung am Mittelwert</h2>
<p>Wenn wir auch die Haupteffekte sinnvoll interpretieren wollen, müssen wir zuvor die Daten am Mittelwert zentrieren. Dies bedeutet, dass wir von jedem beobachteten Wert einer Variablen den Mittelwert dieser Variablen abziehen. Hierzu fügen wir einfach das Argument center = 1 zur “process” Funktion hinzu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"av"</span>, <span class="at">x =</span> <span class="st">"uv"</span>, <span class="at">w =</span> <span class="st">"W"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">1</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.2</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="dv">1</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
           
  Model: 1 
      Y: av
      X: uv
      W: W 

Sample size: 211


*********************************************************************** 
Outcome Variable: av

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.50       0.25       0.66      22.54       3.00     207.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       2.86       0.06      51.14       0.00       2.75       2.97
uv             0.12       0.11       1.05       0.30      -0.10       0.34
W              0.20       0.03       7.30       0.00       0.15       0.26
int_1          0.20       0.06       3.64       0.00       0.09       0.31

Product terms key:
int_1  :  uv  x  W      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.05      13.25       1.00     207.00       0.00
----------
Focal predictor: uv (X)
      Moderator: W (W)

Conditional effects of the focal predictor at values of the moderator(s):
           W     effect         se          t          p       LLCI       ULCI
       -1.79      -0.24       0.15      -1.62       0.11      -0.54       0.05
       -0.58       0.00       0.12       0.01       0.99      -0.23       0.23
        1.82       0.48       0.15       3.21       0.00       0.19       0.78

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the 16th, 50th, and 84th percentiles.
 
NOTE: The following variables were mean centered prior to analysis: 
         W uv</code></pre>
</div>
</div>
<p>Die Koeffizienten für den Moderator und für den Interaktionsterm (int_1) bleiben gleich. Der Koeffizient für die UV “frame” hat sich jedoch verändert. Er hat den B-Wert 0.12, was bedeutet, dass Personen mit durchschnittlicher Skepsis (0 = Mittelwert), denen gesagt wurde, der Klimawandel habe die Dürre verursacht (frame = 1), die Zurückhaltung von Hilfe um 0.12 Punkte stärker rechtfertigen als Personen, die diese Information nicht hatten (frame = 0). Dieser Koeffizient ist jedoch statistisch nicht signifikant (p = 0.30), und sollte somit inhaltlich NICHT interpretiert werden.</p>
</section>
<section id="visualisierung-des-interaktionseffekts" class="level2">
<h2 class="anchored" data-anchor-id="visualisierung-des-interaktionseffekts">Visualisierung des Interaktionseffekts</h2>
<p>Mit “plot = 1” können wir den Moderationseffekt visualisieren (ähnlich dem Interaktionsdiagramm bei der Varianzanalyse).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"av"</span>, <span class="at">x =</span> <span class="st">"uv"</span>, <span class="at">w =</span> <span class="st">"W"</span>,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">1</span>, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot =</span> <span class="dv">1</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.3</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
           
  Model: 1 
      Y: av
      X: uv
      W: W 

Sample size: 211


*********************************************************************** 
Outcome Variable: av

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
       0.496      0.246      0.661     22.543      3.000    207.000      0.000

Model: 
              coeff         se          t          p       LLCI       ULCI
constant      2.452      0.149     16.449      0.000      2.158      2.745
uv           -0.562      0.218     -2.581      0.011     -0.992     -0.133
W             0.105      0.038      2.756      0.006      0.030      0.180
int_1         0.201      0.055      3.640      0.000      0.092      0.310

Product terms key:
int_1  :  uv  x  W      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W      0.048     13.250      1.000    207.000      0.000
----------
Focal predictor: uv (X)
      Moderator: W (W)

Conditional effects of the focal predictor at values of the moderator(s):
           W     effect         se          t          p       LLCI       ULCI
       1.592     -0.242      0.149     -1.620      0.107     -0.537      0.052
       2.800      0.001      0.117      0.007      0.994     -0.229      0.231
       5.200      0.484      0.151      3.213      0.002      0.187      0.780

Data for visualizing the conditional effect of the focal predictor:
          uv          W         av
       0.000      1.592      2.619
       1.000      1.592      2.377
       0.000      2.800      2.746
       1.000      2.800      2.747
       0.000      5.200      2.998
       1.000      5.200      3.482</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>Einen etwas schöneren Plot können wir erstellen, wenn wir die Werte aus der untersten Tabelle im Output “Data for visualizing the conditional effect of the focal predictor” händisch in die ersten drei Zeilen des folgenden Codes übertragen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.592</span>,<span class="fl">1.592</span>,<span class="fl">2.80</span>,<span class="fl">2.80</span>,<span class="fl">5.20</span>,<span class="fl">5.20</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.619</span>,<span class="fl">2.377</span>,<span class="fl">2.746</span>,<span class="fl">2.747</span>,<span class="fl">2.998</span>,<span class="fl">3.482</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> y, <span class="at">x =</span> w, <span class="at">pch =</span> <span class="dv">15</span>, <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> label_W,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> label_av)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>legend.txt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"natürliche Ursache (x=0)"</span>, <span class="st">"Klimawandel (x=1)"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend =</span> legend.txt, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w[x<span class="sc">==</span><span class="dv">0</span>], y[x<span class="sc">==</span><span class="dv">0</span>], <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w[x<span class="sc">==</span><span class="dv">1</span>], y[x<span class="sc">==</span><span class="dv">1</span>], <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uebung7_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die obige Grafik zeigt deutlich, dass der Einfluss des Frames auf die Rechtfertigung je nach den Werten des Moderators mehr oder weniger stark ist. Am stärksten ist er bei Teilnehmenden mit hoher Klimaskepsis ausgeprägt.</p>
</section>
<section id="untersuchung-des-interaktionseffekts" class="level2">
<h2 class="anchored" data-anchor-id="untersuchung-des-interaktionseffekts">Untersuchung des Interaktionseffekts</h2>
<p>Um herauszufinden, wie stark der bedingte Effekt der UV auf die AV bei bestimmten Werten des Moderators W ist, und ob dieser signifikant ist, können wir die Interaktion mit verschiedenen Methoden genauer untersuchen. Hierzu lassen wir uns zusätzlich mit dem Argument “jn=1” die Johnson-Neyman-Signifikanzregionen ausgeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"av"</span>, <span class="at">x =</span> <span class="st">"uv"</span>, <span class="at">w =</span> <span class="st">"W"</span>,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">1</span>, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">jn =</span> <span class="dv">1</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.3</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
           
  Model: 1 
      Y: av
      X: uv
      W: W 

Sample size: 211


*********************************************************************** 
Outcome Variable: av

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
       0.496      0.246      0.661     22.543      3.000    207.000      0.000

Model: 
              coeff         se          t          p       LLCI       ULCI
constant      2.452      0.149     16.449      0.000      2.158      2.745
uv           -0.562      0.218     -2.581      0.011     -0.992     -0.133
W             0.105      0.038      2.756      0.006      0.030      0.180
int_1         0.201      0.055      3.640      0.000      0.092      0.310

Product terms key:
int_1  :  uv  x  W      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W      0.048     13.250      1.000    207.000      0.000
----------
Focal predictor: uv (X)
      Moderator: W (W)

Conditional effects of the focal predictor at values of the moderator(s):
           W     effect         se          t          p       LLCI       ULCI
       1.592     -0.242      0.149     -1.620      0.107     -0.537      0.052
       2.800      0.001      0.117      0.007      0.994     -0.229      0.231
       5.200      0.484      0.151      3.213      0.002      0.187      0.780

Moderator value(s) defining Johnson-Neyman significance region(s):
       Value    % below    % above
       1.171      6.635     93.365
       3.934     67.773     32.227

Conditional effect of focal predictor at values of the moderator:
           W     effect         se          t          p       LLCI       ULCI
       1.000     -0.361      0.173     -2.090      0.038     -0.702     -0.020
       1.171     -0.327      0.166     -1.971      0.050     -0.654      0.000
       1.421     -0.277      0.156     -1.774      0.077     -0.584      0.031
       1.842     -0.192      0.141     -1.364      0.174     -0.469      0.086
       2.263     -0.107      0.128     -0.837      0.403     -0.359      0.145
       2.684     -0.022      0.119     -0.189      0.850     -0.256      0.211
       3.105      0.062      0.113      0.550      0.583     -0.161      0.285
       3.526      0.147      0.112      1.308      0.192     -0.075      0.368
       3.934      0.229      0.116      1.971      0.050      0.000      0.458
       3.947      0.232      0.116      1.991      0.048      0.002      0.461
       4.368      0.316      0.125      2.539      0.012      0.071      0.562
       4.789      0.401      0.136      2.940      0.004      0.132      0.670
       5.211      0.486      0.151      3.219      0.001      0.188      0.783
       5.632      0.571      0.167      3.408      0.001      0.241      0.901
       6.053      0.655      0.185      3.535      0.001      0.290      1.021
       6.474      0.740      0.204      3.621      0.000      0.337      1.143
       6.895      0.825      0.224      3.679      0.000      0.383      1.267
       7.316      0.909      0.245      3.718      0.000      0.427      1.392
       7.737      0.994      0.266      3.744      0.000      0.471      1.518
       8.158      1.079      0.287      3.762      0.000      0.513      1.644
       8.579      1.163      0.308      3.773      0.000      0.556      1.771
       9.000      1.248      0.330      3.781      0.000      0.597      1.899

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>Folgende drei Tabellen schauen wir uns genauer an:</p>
<ul>
<li><p>Conditional effects of the focal predictor at values of the moderator(s): zeigt die konditionalen Effekte der UV beim 16., 50. und 84. Perzentil der Verteilung der Moderatorvariablen (entspricht bei exakter Normalverteilung einer Standardabweichung unter dem Mittelwert, dem Mittelwert und einer Standardabweichung über dem Mittelwert). Dies sagt uns, wie der konditionale Effekt bei den Teilnehmenden ausfällt, bei denen die Moderatorvariable „relativ niedrig“, „moderat“ und „relativ hoch“ ausgeprägt ist. In unserem Beispiel wird der Effekt nur bei den Befragten mit hoher Klimaskepsis signifikant.</p></li>
<li><p>Moderator value(s) defining Johnson-Neyman significance region(s): zeigt einen oder zwei Werte des Moderators, über oder unter denen ein signifikanter Effekt auftritt. Wird kein Wert angegeben, sind die Effekte über den gesamten Bereich des Moderators statistisch signifikant oder überhaupt nicht statistisch signifikant. In unserem Beispiel sind die Werte bei geringer Klimaskepsis (unter 1.17) und hoher Klimaskepsis (über 3.93) statistisch signifikant, im mittleren Wertebereich des Moderators jedoch nicht.</p></li>
<li><p>Conditional effect of focal predictor at values of the moderator: zeigt den bedingten Effekt über viele verschiedene Werte des Moderators hinweg. Auch hier lassen sich die signifikanten Wertebereiche in der Spalte mit den p-Werten identifizieren. Unter 1.17 und über 3.95 sind die p-Werte signfikant.</p></li>
</ul>
</section>
<section id="zum-nachlesen" class="level2">
<h2 class="anchored" data-anchor-id="zum-nachlesen">Zum Nachlesen</h2>
<p>Grundlage dieses Tutorials ist folgendes Buch: Hayes, A.F. (2022). Introduction to mediation, moderation, and conditional process analysis : A regression-based approach. Part III. Moderation analysis.</p>
<p>Dieses Skript basiert außerdem in weiten Teilen auf dem ausführlichen Tutorial von Nicola Righetti zur Moderationsanalyse unter diesem Link: <a href="https://nicolarighetti.github.io/mediation-moderation-and-conditional-process-analysis-with-r/moderation.html" class="uri">https://nicolarighetti.github.io/mediation-moderation-and-conditional-process-analysis-with-r/moderation.html</a></p>
<p>Der Datensatz stammt von folgende Studie: Chapman, D. A., &amp; Lickel, B. (2016). Climate Change and Disasters: How Framing Affects Justifications for Giving or Withholding Aid to Disaster Victims. Social Psychological and Personality Science, 7(1), 13-20. <a href="https://doi.org/10.1177/1948550615590448" class="uri">https://doi.org/10.1177/1948550615590448</a></p>
</section>
<section id="hausübung-7" class="level2">
<h2 class="anchored" data-anchor-id="hausübung-7">Hausübung 7</h2>
<p>Jetzt sind Sie dran! Wiederholen Sie die Analyse mit der abhängigen Variablen “donate” im selben Datensatz. UV und Moderatorvariable bleiben gleich.</p>
<ol type="1">
<li>Definieren Sie die Variablen für das Modell.</li>
</ol>
<ol start="2" type="1">
<li>Berechnen Sie die deskriptiven Statistiken für die neue AV.</li>
</ol>
<ol start="3" type="1">
<li>Berechnen Sie ein Moderationsmodell mit mittelwertzentrierten Variablen.</li>
</ol>
<ol start="4" type="1">
<li>Interpretieren Sie die Ergebnisse des Modells.</li>
</ol>
<p>Antwort: …</p>
<ol start="5" type="1">
<li>Visualisieren Sie den potenziellen Interaktionseffekt. Was sehen Sie in der Grafik?</li>
</ol>
<p>Antwort:…</p>
<ol start="6" type="1">
<li>Lassen Sie sich die Johnson-Neyman Signifikanzregionen ausgeben. Wie interpretieren Sie diese?</li>
</ol>
<p>Antwort: …</p>
<p><strong>Wichtig!</strong> Speichern Sie das angepasste Markdown mit einem Dateinamen nach dem folgenden Muster: Nachname_Übung7.Rmd Laden Sie diese Datei in den dafür vorgesehenen Ordner in Moodle.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>