<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annie Waldherr und Antje Sader">
<meta name="dcterms.date" content="2024-04-29">

<title>Übung 4: Mehrfaktorielle Varianzanalyse – R Tutorials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R Tutorials</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lernziele-und-überblick" id="toc-lernziele-und-überblick" class="nav-link active" data-scroll-target="#lernziele-und-überblick">Lernziele und Überblick</a></li>
  <li><a href="#das-arbeitsverzeichnis" id="toc-das-arbeitsverzeichnis" class="nav-link" data-scroll-target="#das-arbeitsverzeichnis">Das Arbeitsverzeichnis</a></li>
  <li><a href="#pakete-installieren-und-laden" id="toc-pakete-installieren-und-laden" class="nav-link" data-scroll-target="#pakete-installieren-und-laden">Pakete installieren und laden</a></li>
  <li><a href="#daten-einlesen" id="toc-daten-einlesen" class="nav-link" data-scroll-target="#daten-einlesen">Daten einlesen</a></li>
  <li><a href="#uvs-und-avs-definieren" id="toc-uvs-und-avs-definieren" class="nav-link" data-scroll-target="#uvs-und-avs-definieren">UVs und AVs definieren</a></li>
  <li><a href="#deskriptive-statistiken-der-av" id="toc-deskriptive-statistiken-der-av" class="nav-link" data-scroll-target="#deskriptive-statistiken-der-av">Deskriptive Statistiken der AV</a></li>
  <li><a href="#levene-test-zur-voraussetzungsprüfung" id="toc-levene-test-zur-voraussetzungsprüfung" class="nav-link" data-scroll-target="#levene-test-zur-voraussetzungsprüfung">Levene-Test zur Voraussetzungsprüfung</a></li>
  <li><a href="#mehrfaktorielle-varianzanalyse" id="toc-mehrfaktorielle-varianzanalyse" class="nav-link" data-scroll-target="#mehrfaktorielle-varianzanalyse">Mehrfaktorielle Varianzanalyse</a></li>
  <li><a href="#effektgrößen" id="toc-effektgrößen" class="nav-link" data-scroll-target="#effektgrößen">Effektgrößen</a></li>
  <li><a href="#ergebnisse-berichten" id="toc-ergebnisse-berichten" class="nav-link" data-scroll-target="#ergebnisse-berichten">Ergebnisse berichten</a></li>
  <li><a href="#visualisierung-der-effekte" id="toc-visualisierung-der-effekte" class="nav-link" data-scroll-target="#visualisierung-der-effekte">Visualisierung der Effekte</a></li>
  <li><a href="#zum-nachlesen" id="toc-zum-nachlesen" class="nav-link" data-scroll-target="#zum-nachlesen">Zum Nachlesen</a></li>
  <li><a href="#hausübung-4" id="toc-hausübung-4" class="nav-link" data-scroll-target="#hausübung-4">Hausübung 4</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Übung 4: Mehrfaktorielle Varianzanalyse</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Annie Waldherr und Antje Sader </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 29, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="lernziele-und-überblick" class="level2">
<h2 class="anchored" data-anchor-id="lernziele-und-überblick">Lernziele und Überblick</h2>
<p>Diese Übung vermittelt die Grundlagen der mehrfaktoriellen Varianzanalyse (ANOVA). Sie lernen, wie man:</p>
<ul>
<li>eine zweifaktorielle Varianzanalyse durchführt und interpretiert,</li>
<li>Effektgrößen berechnet und interpretiert,</li>
<li>Effektgrößen mit Fehlerbalken darstellt,</li>
<li>Interaktionsdiagramme darstellt und interpretiert.</li>
</ul>
</section>
<section id="das-arbeitsverzeichnis" class="level2">
<h2 class="anchored" data-anchor-id="das-arbeitsverzeichnis">Das Arbeitsverzeichnis</h2>
<p>Wie immer prüfen wir zunächst mit “getwd()”, unter welchem Pfad unser Arbeitsverzeichnis abgelegt ist. Alle Skripte und Datensätze, mit denen wir arbeiten wollen, sollten in diesem Ordner gespeichert sein. Sollte dies nicht der Fall sein, definieren wir das Arbeitsverzeichnis neu unter: Session -&gt; Set Working Directory -&gt; Choose Directory.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Arbeitsverzeichnis checken</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/antje/Documents/studium PUK/Master-Publizistik/STUDIENASSISTENZ/Test Tutorial"</code></pre>
</div>
</div>
</section>
<section id="pakete-installieren-und-laden" class="level2">
<h2 class="anchored" data-anchor-id="pakete-installieren-und-laden">Pakete installieren und laden</h2>
<p>Im Folgenden benötigen wir dieselben Pakete wie bei Übung 3. Diese laden wir wieder mit dem Paket “pacman”, welches wir bereits in Übung 2 (t-Test) installiert haben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Pakete installieren und laden</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>); <span class="fu">library</span>(pacman)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: pacman</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(mosaic, knitr, tidyverse, effectsize, broom, car, ggpubr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="daten-einlesen" class="level2">
<h2 class="anchored" data-anchor-id="daten-einlesen">Daten einlesen</h2>
<p>In einem Experiment von Arendt et al.&nbsp;(2023) (N=827) wurde untersucht, ob Nachrichtenmedien politisches Zuhören gegenüber anderen Meinungen erhöhen können, indem sie die Salienz von Parteihinweisen reduzieren.</p>
<p>Die Studie finden Sie auch auf Moodle:</p>
<p>Arendt, F., Northup, T., Forrai, M., &amp; Scheufele, D. (2023). Why we stopped listening to the other side: How partisan cues in news coverage undermine the deliberative foundations of democracy. Journal of Communication, 73(5), 413–426. <a href="https://doi.org/10.1093/joc/jqad007" class="uri">https://doi.org/10.1093/joc/jqad007</a></p>
<p>Wir laden den Datensatz “PoliticalListening.csv” aus dem entsprechenden Ordner in Moodle und legen ihn ins Arbeitsverzeichnis.</p>
<p>Er enthält vier Variablen: - SCT (“Senator Choice Task”): Indexwert für selektives politisches Zuhören bei der Auswahl von Reden bekannter Politiker:innen; höhere Werte weisen auf eine größere Bereitschaft hin, politischen Ideen der Republikaner Gehör zu schenken. - HCT (“Headline Choice Task”): wie oben Indexwert für selektives politisches Zuhören, aber bei der Auswahl von Reden unbekannter Politiker:innen - Group: Dies ist die Gruppierungsvariable für die Experimentalbedingung; je nach Gruppe waren die Hinweise auf die Parteizugehörigkeit der Redner:innen mehr oder weniger salient (nicht vorhanden=0; niedrig=1; hoch=2) - ID_dicho: Selbstidentifikation der Teilnehmer:innen mit einer Partei (Demokrat=0; Republikaner=1)</p>
<p>Unsere Aufgabe: Wir überprüfen zunächst, ob selektives politisches Zuhören (Variable „SCT”) von der Salienz der Parteihinweise (Variable „Group”) und der Selbstidentifikation der Teilnehmer:innen mit einer Partei (Variable „ID_dicho”) abhängt.</p>
<p><strong>Achtung!</strong>: Wenn wir den Datensatz mit einem einfachen Dateneditor öffnen, sehen wir, dass das Semikolon als Trennungszeichen verwendet wird. Deshalb verwenden wir im folgenden Befehl das Argument “sep”, mit dem wir das Trennungszeichen festlegen können, wenn es von der Voreinstellung (Komma) abweicht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datensatz laden</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/PoliticalListening.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Datensatz inspizieren</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 827
Columns: 4
$ Group    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ ID_dicho &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ HCT      &lt;int&gt; 5, 5, 4, 6, 5, 5, 3, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 3, 6, 6, 5…
$ SCT      &lt;int&gt; 6, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Group ID_dicho HCT SCT
1     0        0   5   6
2     0        0   5   6
3     0        0   4   6
4     0        0   6   5
5     0        0   5   5
6     0        0   5   5</code></pre>
</div>
</div>
<p>Mit der Funktion “View” können wir uns den Datensatz in einem separaten Fenster anschauen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Viewer öffnen</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uvs-und-avs-definieren" class="level2">
<h2 class="anchored" data-anchor-id="uvs-und-avs-definieren">UVs und AVs definieren</h2>
<p>Wir möchten eine zweifaktorielle Varianzanalyse durchführen und prüfen, ob sich das selektive politische Zuhören der Befragten nach Salienz der Parteihinweise und nach Parteiidentifikation signifikant unterscheidet.</p>
<p>Die Variablen “Group” und “ID_dicho” sind also unsere UVs und müssen daher ein nominales Skalenniveua haben.</p>
<p>Im obigen Output der Funktion “glimpse()” haben wir gesehen, dass die beiden Variablen numerisch kodiert sind (vom Typ “integer” int), auch wenn sie inhaltlich nominalskaliert sind. Daher müssen wir diese in Faktoren umwandeln mit der Funktion “factor”.</p>
<p>Zuerst aber rekodieren wir die Variable “ID_dicho”. Diese ist dichotom kodiert mit 0 = Demokrat und 1 = Republikaner. Da R Nullwerte manchmal als fehlende Werte interpretiert, kodieren wir diese Variable so um, dass alle Nullen mit dem Wert 1 und alle Einsen mit dem Wert 2 ersetzt werden. 1 bedeutet dann männlich, 2 weiblich. Ebenso verfahren wir mit der Variable “Group”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Variable Geschlecht umkodieren</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ID_dicho <span class="ot">&lt;-</span> <span class="fu">Recode</span>((df<span class="sc">$</span>ID_dicho), </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">'0 = 1; 1 = 2'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">Recode</span>((df<span class="sc">$</span>Group), </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">'0 = 1; 1 = 2; 2 = 3'</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 827
Columns: 4
$ Group    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ ID_dicho &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ HCT      &lt;int&gt; 5, 5, 4, 6, 5, 5, 3, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 3, 6, 6, 5…
$ SCT      &lt;int&gt; 6, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3…</code></pre>
</div>
</div>
<p>Nun legen wir UVs und AV fest und wandeln die UVs in Faktoren um. Die Argumente “levels” und “labels” verwenden wir, um die drei Faktorstufen mit ihren zugehörigen Bezeichungen zu speichern.</p>
<ul>
<li>Salienz der Parteihinweise: Der Wert 1 wird damit dem Label “no”, der Wert 2 dem Label “low” und der Wert 3 dem Label “high” zugeordnet.</li>
<li>Parteiidentifikation: Wert 1 steht nach der Rekodierung für Demokrat, Wert 2 für Republikaner.</li>
</ul>
<p><strong>Achtung</strong>! Bestehen die Werte der UVs bereits aus Text, d.h. sind vom Typ “character” (chr), dann können wir einfach die Funktion “as.factor()” verwenden (siehe Übung 2).</p>
<p>Die Variable “SCT” ist unsere AV und ist bereits wie gewünscht metrisch skaliert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Unabhängige und abhängige Variablen definieren</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#die UVs wandeln wir in Faktoren um</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>uv1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Group, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span> (<span class="dv">1</span>,<span class="dv">2</span>, <span class="dv">3</span>), </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"low"</span>, <span class="st">"high"</span>)) </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>uv2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>ID_dicho, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span> (<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"democrat"</span>, <span class="st">"republican"</span>)) </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>av <span class="ot">&lt;-</span> df<span class="sc">$</span>SCT</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 827
Columns: 7
$ Group    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ ID_dicho &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ HCT      &lt;int&gt; 5, 5, 4, 6, 5, 5, 3, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 3, 6, 6, 5…
$ SCT      &lt;int&gt; 6, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3…
$ uv1      &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…
$ uv2      &lt;fct&gt; democrat, democrat, democrat, democrat, democrat, democrat, d…
$ av       &lt;int&gt; 6, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3…</code></pre>
</div>
</div>
</section>
<section id="deskriptive-statistiken-der-av" class="level2">
<h2 class="anchored" data-anchor-id="deskriptive-statistiken-der-av">Deskriptive Statistiken der AV</h2>
<p>Nun lassen wir uns zunächst mit der Funktion “favstats” die wichtigsten deskriptiven Statistiken ausgeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Labels vergeben</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>label_uv1 <span class="ot">&lt;-</span> <span class="st">"Salienz der Parteihinweise"</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>label_uv2 <span class="ot">&lt;-</span> <span class="st">"Parteiidentifikation"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>label_av <span class="ot">&lt;-</span> <span class="st">"selektives politisches Zuhören"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Deskriptive Statistiken berechnen</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>des_stat1 <span class="ot">&lt;-</span> <span class="fu">favstats</span>(df<span class="sc">$</span>av <span class="sc">~</span> df<span class="sc">$</span>uv1)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>des_stat2 <span class="ot">&lt;-</span> <span class="fu">favstats</span>(df<span class="sc">$</span>av <span class="sc">~</span> df<span class="sc">$</span>uv2)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabellen erstellen</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span> (des_stat1,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">col.names =</span> <span class="fu">c</span>(label_uv1,<span class="st">"Minimum"</span>, <span class="st">"1.Quartil"</span>, </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Median"</span>, <span class="st">"3.Quartil"</span>, <span class="st">"Maximum"</span>, </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"M"</span>, <span class="st">"SD"</span>, <span class="st">"N"</span>, <span class="st">"Fehlend"</span> ),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 29%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Salienz der Parteihinweise</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">1.Quartil</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">3.Quartil</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Fehlend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">no</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3.60</td>
<td style="text-align: right;">2.20</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">low</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">high</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3.82</td>
<td style="text-align: right;">2.98</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span> (des_stat2,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">col.names =</span> <span class="fu">c</span>(label_uv2,<span class="st">"Minimum"</span>, <span class="st">"1.Quartil"</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Median"</span>, <span class="st">"3.Quartil"</span>, <span class="st">"Maximum"</span>, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"M"</span>, <span class="st">"SD"</span>, <span class="st">"N"</span>, <span class="st">"Fehlend"</span> ),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parteiidentifikation</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">1.Quartil</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">3.Quartil</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Fehlend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">democrat</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1.84</td>
<td style="text-align: right;">1.62</td>
<td style="text-align: right;">456</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">republican</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6.01</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wir sehen, dass sich die Mittelwerte mit der Salienz der Parteihinweise zunehmen. Auch unterscheiden sie sich deutlich je nach Parteiidentifikation. Das bedeutet jedoch nicht, dass diese Unterschiede auch statistisch signifikant sind. Um dies zu prüfen, führen wir im folgenden eine zweifaktorielle Varianzanalyse durch.</p>
<p>Zunächst gruppieren wir den Datensatz nach den beiden UVs mit der Funktion “group_by” und lassen uns hierfür zusammenfassende Statistiken für unsere AV mit der Funktion “summarize”ausgeben: Mittelwerte (mean = mean (av)), Standardabweichungen (std_dev = sd(av)) und die Anzahl der Werte pro Gruppe (count = n()). Um die verschiedenen Arbeitsschritte aneinanderzuhängen verwenden wir wieder die Pfeife (%&gt;%). Den neuen Datensatz speichern wir in einem neuen Objekt namens “df_by_group”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistiken nach Gruppen</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df_by_group <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(uv1, uv2) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(av), <span class="at">std_dev =</span> <span class="fu">sd</span>(av), <span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'uv1'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_by_group</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   uv1 [3]
  uv1   uv2         mean std_dev count
  &lt;fct&gt; &lt;fct&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;
1 no    democrat    2.34    1.53   156
2 no    republican  5.24    1.82   120
3 low   democrat    1.67    1.66   166
4 low   republican  6.33    1.82   129
5 high  democrat    1.46    1.53   134
6 high  republican  6.41    1.80   122</code></pre>
</div>
</div>
<p>In der Spalte “mean” sehen wir für die Republikaner und Demokraten durchaus Unterschiede im selektiven politischen Zuhören (unserer AV!).</p>
</section>
<section id="levene-test-zur-voraussetzungsprüfung" class="level2">
<h2 class="anchored" data-anchor-id="levene-test-zur-voraussetzungsprüfung">Levene-Test zur Voraussetzungsprüfung</h2>
<p>Prüfen wir zunächst, ob die Voraussetzung der Varianzhomogenität vorliegt. Hierzu verwenden wir wieder den Levene-Test, mit dem wir testen, ob sich die Varianzen in allen sechs Gruppen signifikant voneinander unterscheiden. Die unten stehenden Befehle sind bereits aus der vorigen Übung bekannt. Da wir nun aber zwei UVs haben, kombinieren wir diese in der Form: uv1*uv2</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(uv1, uv2, av) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">leveneTest</span>(av <span class="sc">~</span> uv1<span class="sc">*</span>uv2, <span class="at">data =</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value  Pr(&gt;F)  
group   5  2.1921 0.05324 .
      821                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Der Levene-Test ist gerade nicht signifikant (F(5,821) = 2.19, p = 0.05), denn p &gt; 0.05. Somit können wir die Nullhypothese beibehalten, von Varianzhomogenität ausgehen und mit der Varianzanalyse fortfahren.</p>
</section>
<section id="mehrfaktorielle-varianzanalyse" class="level2">
<h2 class="anchored" data-anchor-id="mehrfaktorielle-varianzanalyse">Mehrfaktorielle Varianzanalyse</h2>
<p>Für die Varianzanalyse verwenden wir wieder die Funktion “aov”. Auch in dieser Funktion geben wir die beiden UVs mit * verbunden ein. Dadurch legen wir fest, dass beide Faktoren einzeln auf ihre jeweiligen Haupteffekte sowie in Kombination, d.h. als Interaktionseffekt, getestet werden. Will man die beiden Faktoren getrennt voneinander prüfen, also keinen Interaktionseffekt berechnen, verbindet man sie mit einem +.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(df, uv1, uv2, av)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(av <span class="sc">~</span> uv1<span class="sc">*</span>uv2, <span class="at">data =</span> df)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq  F value               Pr(&gt;F)    
uv1           2      6       3    1.116                0.328    
uv2           1   3548    3548 1244.230 &lt; 0.0000000000000002 ***
uv1:uv2       2    165      83   28.999    0.000000000000677 ***
Residuals   821   2341       3                                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Im Output wird nun eine Tabelle mit vier Zeilen angezeigt. Die Spalten entsprechen genau denen der einfaktoriellen Varianzanalyse (siehe Übung 3). Die Zeile “uv1” beinhaltet die Statistiken für den Haupteffekt unserer ersten UV (Salienz der Parteihinweise), die Zeile “uv2” entsprechend die Statistiken für den Haupteffekt unserer zweiten UV (Parteiidentifikation). Der Haupteffekt für Parteiidentifikation ist höchst signifikant mit p &lt; 0.001. Wir sehen in der letzten Spalte, dass auch der Interaktionseffekt höchst signifikant ist mit p &lt; 0.001 d.h. die Wirkung von Salienz und Parteiidentifikation ist nicht unabhängig voneinander. Der Haupteffekt für die UV1 ist hingegen nicht signifikant (p = 0.328 und damit &gt; 0.05).</p>
<p>Die Werte in der vierten Zeile (Residuals) beziehen sich auf die Varianz innerhalb der Gruppen, die nicht durch die UVs und/oder ihren Interaktionseffekt erklärt werden kann (wird auch Fehlervarianz genannt).</p>
</section>
<section id="effektgrößen" class="level2">
<h2 class="anchored" data-anchor-id="effektgrößen">Effektgrößen</h2>
<p>Um festzustellen, wie groß der Einfluss der UVs auf die AV genau ist, und um die Größe der verschiedenen signifikanten (!) Effekte miteinander vergleichen zu können, bestimmen wir die Effektgrößen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter | Eta2 (partial) |       95% CI
-----------------------------------------
uv1       |       2.71e-03 | [0.00, 1.00]
uv2       |           0.60 | [0.57, 1.00]
uv1:uv2   |           0.07 | [0.04, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p><strong>Wichtig!</strong> Wir interpretieren immer nur die Effektgrößen der signifikanten Effekte, hier also für den Haupteffekt von UV2 und den Interaktionseffekt. Das Eta-Quadrat ist 0.60 für unsere zweite UV und 0.07 für den Interaktionseffekt. Nach Cohen sind dies ein großer bzw ein mittelgroßer Effekt (klein = 0.01; mittel = 0.06; groß = 0.14).</p>
<p><strong>Anmerkung:</strong> Die partiellen Eta-Quadrate werden hier nach der Typ1-Methode berechnet. Das bedeutet, dass die Effektgrößen jeweils um den Effekt der vorigen Variablen bereinigt werden, d.h. aus dem Effekt von UV2 wurde der Effekt von UV1 herausgerechnet, und aus dem Effekt der Interaktion wurde der Effekt der beiden Haupteffekte herausgerechnet.</p>
</section>
<section id="ergebnisse-berichten" class="level2">
<h2 class="anchored" data-anchor-id="ergebnisse-berichten">Ergebnisse berichten</h2>
<p>Wir berichten die Ergebnisse der zweifaktoriellen Varianzanalyse wie folgt:</p>
<p>Der Haupteffekt der Parteiidentifikation auf das selektive politische Zuhören ist signifikant. Die Befragten wählen eher die Reden der Senator:innen aus, die der Partei angehören, mit der sie sich selbst identifizieren, und diese Unterschiede sind signifikant mit F (1,821) = 1244.23,p &lt; 0.001, η² = 0.60.</p>
<p>Auch der Interaktionseffekt ist signifikant mit F (2,821) = 28.99, p &lt; 0.001, η² = 0.07.</p>
<p>Der Haupteffekt der Salienz von Parteihinweisen (p = 0.328) ist hingegen nicht signifikant.</p>
</section>
<section id="visualisierung-der-effekte" class="level2">
<h2 class="anchored" data-anchor-id="visualisierung-der-effekte">Visualisierung der Effekte</h2>
<p>Wir erstellen nun ein Liniendiagramm mit Fehlerbalken, welches den Haupteffekt unserer UV2 Parteiidentifikation visualisiert. Zuerst erstellen wir eine Variable namens “Titel” und weisen ihr den Titel zu, den wir der Grafik geben wollen: “Effekt für Parteiidentifikation”</p>
<p>Anschließend verwenden wir die ggline-Funktion aus dem ggpubr-Paket, um ein Liniendiagramm zu erstellen. Wir nehmen unseren Datensatz “df” und entfernen mit “drop_na()”zunächst alle Zeilen mit fehlenden Werten für unsere UV2 und AV. Dann geben wir an, welche Variablen für die x-Achse und die y-Achse des Diagramms verwendet werden sollen. Die UV2 setzen wir auf die x-Achse, und die AV auf die y-Achse.</p>
<p>Wir legen mit dem Argument “title = Titel” den oben gewählten Titel als Titel für die Grafik fest und fügen mit “add” die 95%-Konfidenzintervallen als Fehlerbalken hinzu (mean_ci). Schließlich legen wir mit “xlab” und “ylab” die Beschriftungen der Grafikachsen fest, wobei wir auf unsere oben erstellten Labels (siehe Code-Chunk “Deskriptive Statistiken”) verweisen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>Titel <span class="ot">&lt;-</span> <span class="st">"Effekt für Parteiidentifikation"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggline</span>(df <span class="sc">%&gt;%</span> <span class="fu">drop_na</span> (av, uv2),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">"uv2"</span>, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"av"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> Titel,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">add =</span> <span class="st">"mean_ci"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> label_uv2,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> label_av)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Varianzanalyse2_files/figure-html/Fehlerbalken-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Als Ergebnis erhalten wir ein Liniendiagramm, das die Mittelwerte des selektiven politischen Zuhörens (AV) nach Parteiidentifikation (UV2) zeigt. Die Konfidenzintervalle zeigen den Werteraum an, in dem die wahren Mittelwerte mit 95% Sicherheit liegen. Diese überlappen sich nicht, die Unterschiede sind also signifikant.</p>
<p>Um beide Haupteffekte und ihre Interaktion zu visualisieren, eignet sich ein Interaktionsdiagramm. Dieses erstellen wir mit der Funktion “interaction.plot” aus dem Paket “stats”. Wir legen folgende Argumente fest:</p>
<ul>
<li>df$uv1: Die Werte von UV1 werden auf der x-Achse dargestellt.</li>
<li>df$uv2: Die Werte von UV2 werden verwendet, um verschiedene Linien im Plot zu erzeugen.</li>
<li>df$av: Die Werte unserer AV werden auf der y-Achse dargestellt.</li>
<li>fun = mean: Die Funktion “mean” wird verwendet, um die Mittelwerte von AV für jedes Faktorlevel von UV1 und UV2 zu berechnen. Diese werden verwendet, um die Linien im Plot zu erzeugen.</li>
<li>ylab = label_uv1: Das Label für die y-Achse wird auf “label_uv1” gesetzt, welches wir oben festgelegt haben.</li>
<li>xlab = label_av: Das Label für die x-Achse wird auf “label_av” gesetzt, welches wir ebenfalls breits oben definiert haben.</li>
<li>trace.label = label_uv2: Die Legende für die Linien im Plot wird mit “label_uv2” beschriftet.</li>
<li>col = c(“#0198f9”, “#f95801”): Die Farben für die Linien werden auf Blau und Orange gesetzt.</li>
<li>lty = 1: Der Linientyp für die Linien wird als volle Linie (lty=1) festgelegt.</li>
<li>lwd = 2: Die Dicke der Linien wird auf 2 gesetzt.</li>
<li>xtick = TRUE: Gitterlinien für die x-Achse werden angezeigt.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>uv1, df<span class="sc">$</span>uv2, df<span class="sc">$</span>av,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="at">fun =</span> mean,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="at">ylab =</span> label_av,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> label_uv1,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="at">trace.label =</span> label_uv2,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#0198f9"</span>, <span class="st">"#f95801"</span>),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">1</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="at">xtick =</span> T,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Varianzanalyse2_files/figure-html/Interaktionsdiagramm-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wir sehen, dass es sich hier um eine ordinale Interaktion handelt. Bereits in der Kontrollgruppe gibt es einen signifikanten Unterschied in der Auswahl der Reden von Republikanern und Demokraten je nach Parteiidentifikation. Selektives politisches Zuhören (d.&nbsp;h. die Differenz in der AV zwischen selbstidentifizierten Republikanern und Demokraten) nimmt mit der Salienz der Parteihinweise zu, d.&nbsp;h. die Salienz von Parteihinweisen moderiert die Beziehung zwischen Parteiidentifikation und selektivem politischem Zuhören.</p>
</section>
<section id="zum-nachlesen" class="level2">
<h2 class="anchored" data-anchor-id="zum-nachlesen">Zum Nachlesen</h2>
<p>Kapitel 12.5 in: Gehrau, V., Maubach, K., Fujarski, S. (2022). Einfache Datenauswertung mit R. Springer.</p>
<p>Kapitel 10.3.2 in: Manderscheid, K. (2017). Sozialwissenschaftliche Datenanalyse mit R, 2. Aufl. Springer.</p>
</section>
<section id="hausübung-4" class="level2">
<h2 class="anchored" data-anchor-id="hausübung-4">Hausübung 4</h2>
<p>Wiederholen Sie nun die Analysen für die “Headline Choice Task” (HTC), in der Reden unbekannter Politiker:innen ausgewählt wurden (die vierte, bisher ungenutzte Variable im Datensatz). Prüfen Sie auch hier, ob das selektive politische Zuhören von der Salienz der Parteihinweise (nicht vorhanden=0; niedrig=1 hoch=2) und der Parteiidentifikation (Demokrat=0; Republikaner=1) abhängt.</p>
<ol type="1">
<li>Definieren Sie die neue abhängige Variable.</li>
</ol>
<ol start="2" type="1">
<li>Lassen Sie sich die deskriptiven Statistiken für die neue abhängige Variable ausgeben, gruppiert nach den UVs.</li>
</ol>
<ol start="3" type="1">
<li>Prüfen Sie, ob die Daten die Voraussetzung der Varianzhomogenität erfüllen. Führen Sie den entsprechenden Test durch und interpretieren Sie das Ergebnis.</li>
</ol>
<p>Antwort:</p>
<ol start="4" type="1">
<li>Führen Sie nun eine mehrfaktorielle Varianzanalyse durch. Wie interpretieren Sie die Ergebnisse inhaltlich? Gehen Sie dabei auf jeden einzelnen Effekt ein.</li>
</ol>
<p>Antwort: …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Varianzanalyse durchführen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" type="1">
<li>Berechnen Sie die Effektgrößen und machen Sie eine Aussage zur Stärke der signifikanten Effekte.</li>
</ol>
<p>Antwort:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Effektgrößen berechnen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="6" type="1">
<li>Haben Sie eine signifikante Interaktion gefunden? Wenn ja, stellen Sie den Interaktionseffekt graphisch dar und erklären Sie die Art der Interaktion. Wenn nein, dann stellen Sie nur die signifikanten Haupteffekte mit Fehlerbalken graphisch dar.</li>
</ol>
<p>Antwort:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Interaktionsplot oder Liniendiagramm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Wichtig!</strong> Speichern Sie das angepasste Markdown mit einem Dateinamen nach dem folgenden Muster: Nachname_Übung4.Rmd Laden Sie diese Datei in den dafür vorgesehenen Ordner in Moodle.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>